package(default_visibility = ["//visibility:public"])

proto_library(
    name = "protobuf-c_proto",
    srcs = ["protobuf-c.proto"],
    strip_import_prefix = "/proto",
    deps = ["@protobuf//:descriptor_proto"],
)
