package(default_visibility = ["//visibility:public"])

cc_test(
    name = "test_version",
    srcs = glob(["*.c"]),
    includes = ["."],
    deps = [
        "//:base",
        "//protobuf-c:protobuf-c",
    ],
)
