package(default_visibility = ["//visibility:public"])

cc_test(
    name = "version",
    srcs = glob(["*.c"]),
    includes = ["."],
    deps = [
        "//:base",
        "//protobuf-c:protobuf-c",
    ],
)
