package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ver",
    defines = [
        'PACKAGE_VERSION=\\"1.5.2\\"',
        'PACKAGE_STRING=\\"protobuf-c_1.5.2\\"',
    ],
)
